name: Continuous Integration
on:
  push:
    branches: "main"

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
          extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath, curl, zip, gd, dom, fileinfo, openssl, tokenizer
          coverage: none
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Create required directories
        run: |
          mkdir -p bootstrap/cache
          mkdir -p storage/framework/cache
          mkdir -p storage/framework/sessions
          mkdir -p storage/framework/views
          mkdir -p storage/logs
      
      - name: Set Directory Permissions
        run: chmod -R 775 storage bootstrap/cache
      
      - name: Configure Environment for Testing
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=database/database.sqlite" >> .env
          echo "CACHE_DRIVER=array" >> .env
          echo "SESSION_DRIVER=array" >> .env
      

          echo "QUEUE_DRIVER=sync" >> .env
      
      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      
      - name: Install Dependencies
        run: |
          composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
      
      - name: Generate Application Key
        run: php artisan key:generate
      
      - name: Clear Config and Cache
        run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan view:clear
      
      - name: Optimize Autoloader
        run: composer dump-autoload --optimize
      
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install npm Dependencies
        run: |
          npm install
          npm cache clean --force
      
      - name: Build Frontend Assets
        run: npm run build
      
      - name: Fix Migration Issue
        run: |
          # Fix the duplicate primary key issue in countries migration
          sed -i '/\$table->primary(.id.);/d' database/migrations/2024_08_02_061808_create_countries_table.php
      
      - name: Run Migrations
        run: php artisan migrate --force
      
      - name: Run Tests
        run: php artisan test --env=testing
      
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            public/
            bootstrap/cache/
            storage/
          retention-days: 7
